name = "azim-crafts"
pages_build_output_dir = "frontend/dist"
compatibility_date = "2024-08-01"

# ==========================================
# 1. CLOUDFLARE D1 SQL DATABASE BINDING
# ==========================================
[[d1_databases]]
binding = "DB"
database_name = "azimcrafts-db"
database_id = "a50e61cb-1c69-4eb6-a157-9a76d2d57f49"

# ==========================================
# 2. ENVIRONMENT VARIABLES
# ==========================================
[vars]
STORE_EMAIL = "contact@azimcrafts.com"
EMAIL_FROM = "Azim Crafts <contact@azimcrafts.com>"
